baseURL = "https://www.marcelwagenlaender.com"
languageCode = "en-gb"
title = "Marcel Wagenländer"

[params]
    dateFormat = "2 January 2006"
    description = "Marcel Wagenländer — AI Systems Researcher"
    author = "Marcel Wagenländer"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

[[params.social]]
    name = "mastodon"
    url  = "https://mastodon.social/@marcelwagenlander"
[[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/marcel-wagenlaender"
[[params.social]]
    name = "scholar"
    url  = "https://scholar.google.com/citations?user=HrCWNs0AAAAJ"
[[params.social]]
    name = "github"
    url  = "https://github.com/marwage"
[[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/marcelsperspective"
[[params.social]]
    name = "bluesky"
    url  = "https://bsky.app/profile/marcelwagenlander.com"
[[params.social]]
    name = "email"
    url  = "mailto:helloαmarcel.systems"
