baseURL = "https://www.marcelwagenlaender.net"
languageCode = "en-gb"
title = "Marcel Wagenländer"
theme = "introduction"

[params]
    themeStyle                   = "light"                 # Choose "light" or "dark" or "auto"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = false                   # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "2 January 2006"
    email                        = "youremail@email.com"   # E-mail address for contact section
    # customCSS                  = ["bar.css"]             # Include custom css files placed under assets/
    # customJS                   = ["foo.js"]              # Include custom JavaScript files placed under assets/

    # Configure the home page
    [params.home]
        introHeight              = "medium"                # Input either "medium" or "large" or "fullheight"
        showLatest               = true                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat    = true                    # show all posts in an archive format
        numberOfProjectsToShow   = 3                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = false                   # Show your current local time in contact section
        timeZone                 = "Europe/London"         # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "en-GB"                 # Language specific format to use
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://mastodon.social/@marcelwagenlander"
        icon  = "mastodon" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://www.linkedin.com/in/marcel-wagenländer-85844715b"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
    [[params.social]]
        url   = "https://scholar.google.com/citations?user=HrCWNs0AAAAJ"
        icon  = "graduation-cap" # icon name without the 'fa-'
        icon_pack = "fas"
    [[params.social]]
        url = "https://github.com/marwage"
        icon = "github"
        icon_pack = "fab"
    [[params.social]]
        url = "https://www.instagram.com/marcelsperspective"
        icon = "instagram"
        icon_pack = "fab"
    [[params.social]]
        url = "https://www.threads.net/@marcelsperspective"
        icon = "threads"
        icon_pack = "fas"
    # [[params.social]]
        # url = "mailto:youremail@email.com"  # For a direct email link, use "mailto:test@example.org".
        # icon = "paper-plane" # icon name without the 'fa-'
        # icon_pack = "fas"
